### ISSUE TITLE
GH Workflow `PULL BUILD IMAGE` is failing

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma-companion#327]
- [issues](https://github.com/kyma-project/kyma-companion/issues/327)
- [overview of runs](https://github.com/kyma-project/kyma-companion/actions/workflows/pull-build-image.yaml)
- [`Pull Build Image` gh workflow](https://github.com/kyma-project/kyma-companion/actions/runs/12668229125/workflow)
- [`image-builder` gh workflow on test-infra](https://github.com/kyma-project/test-infra/blob/main/.github/workflows/image-builder.yml)
- [`image-builder` gh action](https://github.com/kyma-project/test-infra/blob/main/.github/actions/image-builder/action.yml)
- [change notes](https://python-poetry.org/blog/announcing-poetry-2.0.0/) 
- [CLI docs](https://python-poetry.org/docs/cli/) 
## Questions:
- Where is the image that causes issues referenced?
```
Unable to find image 'gcr.io/kaniko-project/executor@sha256:c3109d5926a997b100c4343944e06c6b30a6804b2f9abe0994d3de6ef92b028e' locally
```
### Flow
The job `PULL BUILD IMAGE` fails.
The [workflow](https://github.com/kyma-project/kyma-companion/actions/runs/12668229125/workflow) fails at its first step `build` which uses the `image-builder` workflow flow test-infra:
```
jobs:
  build:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
```
The [`image-builder` gh workflow on test-infra](https://github.com/kyma-project/test-infra/blob/main/.github/workflows/image-builder.yml) is failing at the step `Build Image` which uses the `image-builder` action.
```
      - name: Build image
        id: build
        uses: ./.github/actions/image-builder
        with:
          oidc-token: ${{ steps.get_oidc.outputs.jwt }}
          ado-token: ${{ steps.secrets.outputs.ado-pat }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          tags: ${{ inputs.tags }}
          export-tags: ${{ inputs.export-tags }}
          image-name: ${{ inputs.name }}
          dockerfile: ${{ inputs.dockerfile }}
          env-file: ${{ inputs.env-file }}
          config: "./configs/image-builder-client-config.yaml"
          use-go-internal-sap-modules: ${{ inputs.use-go-internal-sap-modules }}
```
(it also uses [this](https://github.com/kyma-project/test-infra/blob/main/configs/image-builder-client-config.yaml) config which seems to be not causing any issues)

Finally the [`image-builder` action fails](https://github.com/kyma-project/test-infra/blob/main/.github/actions/image-builder/action.yml).
### Error
The first error occurs because the build image cannot be found **locally**:
```
Unable to find image 'gcr.io/kaniko-project/executor@sha256:c3109d5926a997b100c4343944e06c6b30a6804b2f9abe0994d3de6ef92b028e' locally
```
This seems to be a simple check and should not return an error.

Then the job tries to pull the image which is also shown as an error:
```
gcr.io/kaniko-project/executor@sha256:c3109d5926a997b100c4343944e06c6b30a6804b2f9abe0994d3de6ef92b028e: Pulling from kaniko-project/executor
```
We also receive the error
```
Error: INFO[0001] No cached layer found for cmd RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi && pip uninstall -y poetry
```
## Solution
The `--no-dev` option in the command `peotry install --no-dev` caused the problem. The option was deprecated for a while and with the release of Poetry 2.0 got completely removed. Poetry 2.0 was released on Jan 5th 2025. The [change notes](https://python-poetry.org/blog/announcing-poetry-2.0.0/) do not mention this change directly but it cannot be found in the [CLI docs](https://python-poetry.org/docs/cli/) anymore.

Old:
```
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi \
    && pip uninstall -y poetry
```
Proposed changes
```
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
	    && poetry install --no-interaction --no-ansi \
    && pip uninstall -y poetry
```
### pin to a certain version via brew
The problem appeared because we install `Poetry` without any specific version. `Poetry` got updated and this broke our GH Workflow. We could avoid this by pinning the `pip install` statement to a concrete version.
Old:
```
RUN pip install --no-cache-dir poetry \
    ...
```
New:
```
RUN pip install --no-cache-dir poetry=2.0.0 \
    ...
```
note: maybe pin to major version?
note: is there a way to pin the version int the project.toml?
### the --without option
To recreate the original functionality we might wan to use the [`--without` option](https://python-poetry.org/docs/cli/#install):
```
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --without dev --no-interaction --no-ansi \
    && pip uninstall -y poetry
```
we might also remove the test packages, as proposed in the docs:
```
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --without dev,test --no-interaction --no-ansi \
    && pip uninstall -y poetry
```
