### ISSUE TITLE
We need to remove problem cause from test Resources and its namespaces

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma-companion#509]
Currently, resource have short problem cause in the namespace or resource names. We need to get rid of them as it is helping LLMs to identify the issue without analysing the content.

For example,
There is a function in `kyma-app-serverless-syntax-err` namespace:

```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: func1
  namespace: kyma-app-serverless-syntax-err
...
```
